version: '3'
services:

  admin:
#    image: cpatrut/mail-sender:1.0.3
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.5
    ports:
     - "5432:5432"